name: Check

on:
  push:
    branches:
      - main
      - conan2_new

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  run-check:
    name: Run check
    uses: ./.github/workflows/run-check.yaml
    secrets:
      YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      YC_VM_USERNAME: ${{ secrets.YC_VM_USERNAME }}
      YC_VM_SSH_PUBLIC_KEY: ${{ secrets.YC_VM_SSH_PUBLIC_KEY }}

