name: Check

on:
  workflow_call:
    inputs:
      commit-sha:
        required: false
        type: string
    secrets:
      YC_SA_JSON_CREDENTIALS:
        required: true
      GH_PERSONAL_ACCESS_TOKEN:
        required: true
      YC_VM_USERNAME:
        required: true
      YC_VM_SSH_PUBLIC_KEY:
        required: true


env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  start-vm:
    name: Start VM
    runs-on: trampoline
    outputs:
      label: ${{ steps.start-yc-runner.outputs.label }}
      instance-id: ${{ steps.start-yc-runner.outputs.instance-id }}
    steps:
      - name: Start YC runner
        id: start-yc-runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: start
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          folder-id: ${{ vars.YC_FOLDER_ID }}
          image-id: ${{ vars.YC_DEFAULT_IMAGE_ID }}
          zone-id: ${{ vars.YC_ZONE_ID }}
          subnet-id: ${{ vars.YC_SUBNET_ID }}
          cores: 16
          memory: 32GB
          core-fraction: 100
          disk-type: network-ssd-nonreplicated
          disk-size: 279GB
          user: ${{ secrets.YC_VM_USERNAME }}
          ssh-public-key: ${{ secrets.YC_VM_SSH_PUBLIC_KEY }}
          public-ip: false
          runner-home-dir: /actions-runner
          ttl: PT24H

  checkout:
    name: Checkout sources
    needs: start-vm
    runs-on: ${{ needs.start-vm.outputs.label }}
    steps:
      - name: Checkout ytsaurus-cpp-sdk
        uses: actions/checkout@v3

      - name: Checkout PR
        if: ${{ inputs.commit-sha }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit-sha }}

  build:
    name: Build
    needs:
      - start-vm
      - checkout
    runs-on: ${{ needs.start-vm.outputs.label }}
    steps:
      - name: Stop and remove old container
        run: docker rm -f build-container || true

      - name: Run container
        run: docker run -d --name build-container --network host -v "$(pwd)":/ytsaurus-cpp-sdk ghcr.io/ytsaurus/build-env:latest tail -f /dev/null

      - name: Build with libc++
        run: |
          docker exec build-container bash -c '
            set -ex
            /ytsaurus-cpp-sdk/yt/yt/scripts/build_cmake.sh configure \
              --source-path /ytsaurus-cpp-sdk \
              --build-path /build \
              --build-type Release \
              --ccache-remote-storage "${{ vars.CCACHE_REMOTE_STORAGE }}" \
              --ccache-base-dir /ytsaurus-cpp-sdk \
              --cxx-flags-init "-stdlib=libc++"
            /ytsaurus-cpp-sdk/yt/yt/scripts/build_cmake.sh build --build-path /build
          '

      - name: Build with libstdc++
        run: |
          docker exec build-container bash -c '
            set -ex
            /ytsaurus-cpp-sdk/yt/yt/scripts/build_cmake.sh configure \
              --source-path /ytsaurus-cpp-sdk \
              --build-path /build_gcc \
              --build-type Release \
              --ccache-remote-storage "${{ vars.CCACHE_REMOTE_STORAGE }}" \
              --ccache-base-dir /ytsaurus-cpp-sdk \
              --cxx-flags-init "-stdlib=libstdc++ -std=c++20"
            /ytsaurus-cpp-sdk/yt/yt/scripts/build_cmake.sh build --build-path /build_gcc
          '

  stop-vm:
    name: Stop VM
    needs:
      - start-vm
      - build
    runs-on: trampoline
    if: ${{ always() }}
    steps:
      - name: Stop YC runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: stop
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-vm.outputs.label }}
          instance-id: ${{ needs.start-vm.outputs.instance-id }}
